baseURL: 'https://xknt21.github.io/'
languageCode: 'en-us'
title: 'PBL3 Group H'
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: 'tags'

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: PBL3 Group H
  description: 'PBL3 Group H'
  keywords: [Blog, Portfolio, PaperMod]
  author: PBL3 Group H
  images: ['<link or path of image for opengraph, twitter-cards>']
  DateFormat: 'January 2, 2006'
  defaultTheme: light # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: 'PBL3/favicon-3.ico'
    # favicon16x16: '/favicon-16x16.png'
    # favicon32x32: '/favicon-32x32.png'
    # apple_touch_icon: '/apple-touch-icon.png'
    # safari_pinned_tab: '/favicon-16x16.png'

  label:
    text: 'PBL3 Group H'
    icon:
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: PBL3 Group H
    subtitle: 'This is subtitle'
    imageUrl: '<img location>'
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hello world, We are Group H! 👩🏻‍💻"
    Content: |
     # Project Member  
     **Ryusei Fujita - Project Manager**  
     **Kanato Nishiura**  
     **Yukiya Nakamura**  
     **Ananna Taslima Hossain**  
     **Dake Parth**  
     **Huang Chiung-ning**  
     **Jonathan Setiawan**


  socialIcons:
    - name: github
      url: 'https://github.com/xknt21/'
    # - name: youtube
    #   url: 'https://www.youtube.com/c/MagdelineHuang/featured'
    # - name: instagram
    #   url: 'https://www.instagram.com/magdelinehuang/'
    # - name: tiktok
    #   url: 'https://www.tiktok.com/@magdelinehuang'
    # - name: twitter
    #   url: 'https://twitter.com/magdelinehuang'
    # - name: other
    #   url: 'https://beacons.ai/magdelinehuang'

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/xknt21/xknt21.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

menu:
  main:
  
    - identifier: Project Proposal
      name: Project Proposal
      url: /project/
      weight: 10
    - identifier: Requirements Specification
      name: Requirements Specification
      url: /requirements/
      weight: 20
    - identifier: System Design Document
      name: System Design Document
      url: /system/
      weight: 30
    - identifier: System Architecture
      name: System Architecture
      url: /architecture/
      weight: 40
    - identifier: Schedule & Planning
      name: Schedule & Planning
      url: /contents/
      weight: 50
    - identifier: Presentation
      name: Presentation
      url: /presentation/
      weight: 60


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# For search: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# Publishing the site
publishDir: 'public'

